### ISSUE TITLE
subprocess.CalledProcessError: Command '

### ISSUE THREAD

**Issue by xuetingdai** [tianzhi0549/FCOS#118]
Traceback (most recent call last):
  File "tools/train_net.py", line 23, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train_net.py", line 23, in <module>
Traceback (most recent call last):
  File "tools/train_net.py", line 23, in <module>
Traceback (most recent call last):
  File "tools/train_net.py", line 23, in <module>
  File "tools/train_net.py", line 23, in <module>
  File "tools/train_net.py", line 23, in <module>
Traceback (most recent call last):
  File "tools/train_net.py", line 23, in <module>
  File "tools/train_net.py", line 23, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/mnt/nfs/code/zq/FCOS/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from torch.utils.model_zoo import _download_url_to_file
ImportError: cannot import name '_download_url_to_file'
    from torch.utils.model_zoo import _download_url_to_file
    from torch.utils.model_zoo import _download_url_to_file
    from torch.utils.model_zoo import _download_url_to_file
    from torch.utils.model_zoo import _download_url_to_file
ImportError: cannot import name '_download_url_to_file'
ImportError: cannot import name '_download_url_to_file'
ImportError: cannot import name '_download_url_to_file'
ImportError: cannot import name '_download_url_to_file'
    from torch.utils.model_zoo import _download_url_to_file
    from torch.utils.model_zoo import _download_url_to_file
    from torch.utils.model_zoo import _download_url_to_file
ImportError: cannot import name '_download_url_to_file'
ImportError: cannot import name '_download_url_to_file'
ImportError: cannot import name '_download_url_to_file'
Traceback (most recent call last):
  File "/home/zq/anaconda3/envs/retinanet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zq/anaconda3/envs/retinanet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zq/anaconda3/envs/retinanet/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/zq/anaconda3/envs/retinanet/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zq/anaconda3/envs/retinanet/bin/python', '-u', 'tools/train_net.py', '--local_rank=7', '--skip-test', '--config-file', 'configs/fcos/fcos_R_50_FPN_1x.yaml', 'DATALOADER.NUM_WORKERS', '8', 'OUTPUT_DIR', 'train_dir/save_model']' returned non-zero exit status 1.

**Comment by tianzhi0549** [comment]
@xuetingdai please try the latest code.

**Comment by 1356789-rr** [comment]
@tianzhi0549 Hello, I also have similar typing problems, update the latest code after the same error.
Traceback (most recent call last):
  File "tools/train_net.py", line 180, in <module>
    main()
  File "tools/train_net.py", line 152, in main
    cfg.merge_from_file(args.config_file)
  File "/home/rc/anaconda3/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/rc/anaconda3/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/rc/anaconda3/lib/python3.7/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/rc/anaconda3/lib/python3.7/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: DATASETS.RAIN'
Traceback (most recent call last):
  File "/home/rc/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rc/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rc/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/rc/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/rc/anaconda3/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--skip-test', '--config-file', 'configs/fcos/fcos_imprv_R_50_FPN_1x.yaml', 'DATALOADER.NUM_WORKERS', '2', 'OUTPUT_DIR', 'training_dir/fcos_imprv_R_50_FPN_1x']' returned non-zero exit status 1.

**Comment by tianzhi0549** [comment]
@1356789-rr there seems a typo. I think `DATASETS.RAIN` should be `DATASETS.TRAIN`.

**Comment by 1356789-rr** [comment]
@tianzhi0549 Thank you very much!

**Comment by 1356789-rr** [comment]
@tianzhi0549 Sorry to disturb you again! The following mistake I don't know where it happened? There are pictures under the clear path. I used labelimg software to mark pictures to form. XML files and then convert them to JSON files for training. I don't know if it's a conversion problem or a path problem. Want to consult you！
2019-09-18 10:14:44,019 fcos_core.utils.model_serialization INFO: backbone.body.layer4.2.conv2.weight              loaded from layer4.2.conv2.weight        of shape (512, 512, 3, 3)
2019-09-18 10:14:44,020 fcos_core.utils.model_serialization INFO: backbone.body.layer4.2.conv3.weight              loaded from layer4.2.conv3.weight        of shape (2048, 512, 1, 1)
2019-09-18 10:14:44,020 fcos_core.utils.model_serialization INFO: backbone.body.stem.bn1.bias                      loaded from bn1.bias                     of shape (64,)
2019-09-18 10:14:44,020 fcos_core.utils.model_serialization INFO: backbone.body.stem.bn1.weight                    loaded from bn1.weight                   of shape (64,)
2019-09-18 10:14:44,020 fcos_core.utils.model_serialization INFO: backbone.body.stem.conv1.weight                  loaded from conv1.weight                 of shape (64, 3, 7, 7)
2019-09-18 10:14:44,061 fcos_core.data.build WARNING: When using more than one image per GPU you may encounter an out-of-memory (OOM) error if your GPU does not have sufficient memory. If this happens, you can reduce SOLVER.IMS_PER_BATCH (for training) or TEST.IMS_PER_BATCH (for inference). For training, you must also adjust the learning rate and schedule length according to the linear scaling rule. See for example: https://github.com/facebookresearch/Detectron/blob/master/configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml#L14
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2019-09-18 10:14:44,242 fcos_core.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 180, in <module>
    main()
  File "tools/train_net.py", line 173, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 79, in train
    arguments,
  File "/home/rc/下载/FCOS-master_2/fcos_core/engine/trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/rc/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/rc/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/rc/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rc/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rc/下载/FCOS-master_2/fcos_core/data/datasets/coco.py", line 67, in __getitem__
    img, anno = super(COCODataset, self).__getitem__(idx)
  File "/home/rc/anaconda3/lib/python3.7/site-packages/torchvision/datasets/coco.py", line 117, in __getitem__
    img = Image.open(os.path.join(self.root, path)).convert('RGB')
  File "/home/rc/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 2770, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/train2014/000129'

Traceback (most recent call last):
  File "/home/rc/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rc/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rc/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/rc/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/rc/anaconda3/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/fcos/fcos_imprv_R_50_FPN_1x.yaml', 'DATALOADER.NUM_WORKERS', '2', 'OUTPUT_DIR', 'training_dir/fcos_imprv_R_50_FPN_1x']' returned non-zero exit status 1.

**Comment by wanglaotou** [comment]
Hi, i get this error when i trained my model over and start evaluate the model.
![image](https://user-images.githubusercontent.com/12837585/71607806-8050a600-2bb7-11ea-8dcc-c736fb6f8848.png)
my val datasets contains 8871 images and the test batchsize is 8.

**Comment by linsy-ai** [comment]
hello, i meet this problem.

loading annotations into memory...
Done (t=0.54s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
2020-07-15 21:01:45,462 fcos_core.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 180, in <module>
    main()
  File "tools/train_net.py", line 173, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 79, in train
    arguments,
  File "/home/linsy/FCOS/FCOS/fcos_core/engine/trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/linsy/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/linsy/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/linsy/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/linsy/FCOS/FCOS/fcos_core/data/datasets/coco.py", line 78, in __getitem__
    classes = [self.json_category_id_to_contiguous_id[c] for c in classes]
  File "/home/linsy/FCOS/FCOS/fcos_core/data/datasets/coco.py", line 78, in <listcomp>
    classes = [self.json_category_id_to_contiguous_id[c] for c in classes]
KeyError: 1
Traceback (most recent call last):
  File "/home/linsy/anaconda3/envs/FCOS/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/linsy/anaconda3/envs/FCOS/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/linsy/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/linsy/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/linsy/anaconda3/envs/FCOS/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/fcos/fcos_imprv_R_50_FPN_1x.yaml', 'DATALOADER.NUM_WORKERS', '0']' returned non-zero exit status 1.

**Comment by autumnfairytale7** [comment]
> Hi, i get this error when i trained my model over and start evaluate the model.
> ![image](https://user-images.githubusercontent.com/12837585/71607806-8050a600-2bb7-11ea-8dcc-c736fb6f8848.png)
> my val datasets contains 8871 images and the test batchsize is 8.

I also met this problem. Have you solved it?

**Comment by tianzhi0549** [comment]
@autumnfairytale7 Please refer to https://github.com/facebookresearch/detectron2/issues/580#issuecomment-568875006.
