### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by mama110** [tianzhi0549/FCOS#128]
![1](https://user-images.githubusercontent.com/40822074/64219894-f2f79080-cef9-11e9-9266-181088839f0b.png)
When I run the code below(function __call__ in class FCOSLossComputation):
        box_regression_flatten = box_regression_flatten[pos_inds]
        reg_targets_flatten = reg_targets_flatten[pos_inds]
        centerness_flatten = centerness_flatten[pos_inds]

An error shows up as follows:
    reg_targets_flatten = reg_targets_flatten[pos_inds]
RuntimeError: CUDA error: device-side assert triggered

Anyone knows why ? Thanks.

**Comment by mama110** [comment]
solved.

**Comment by liushuai839** [comment]
Hello,guys. When I run the code  that  I  repeat , I met the same error as yours! what  would you do to solve it??
the error as follows:




Traceback (most recent call last):
  File "Quantization/train.py", line 128, in <module>
    train()
  File "Quantization/train.py", line 91, in train
    loss_dict= loss(locations,logits,bbox_reg,centerness,targets)
  File "/home/liushuai/Myworkspace/object_detection/FCOS-master/Quantization/loss.py", line 226, in __call__
    labels, reg_targets = self.prepare_targets(locations, targets)
  File "/home/liushuai/Myworkspace/object_detection/FCOS-master/Quantization/loss.py", line 106, in prepare_targets
    points_all_level, targets, expanded_object_sizes_of_interest
  File "/home/liushuai/Myworkspace/object_detection/FCOS-master/Quantization/loss.py", line 188, in compute_targets_for_locations
    labels_per_im[locations_to_min_area == INF] = 0
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

**Comment by Barnonewdm** [comment]
Could you help indicate the reason or the solution?

**Comment by anchor-wu** [comment]
我遇到了同样的问题，请问有人知道怎么解决么？
