### ISSUE TITLE
How to test on coco

### ISSUE THREAD

**Issue by hheavenknowss** [tianzhi0549/FCOS#137]
Hi there, I tried to run test_net.py on coco datasets, but an issues happend, here is the log:
Traceback (most recent call last):
  File "tools/test_net.py", line 97, in <module>
    main()
  File "tools/test_net.py", line 49, in main
    cfg.merge_from_file(args.config_file)
  File "/usr/local/lib/python3.6/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/private/home/fmassa/github/detectron.pytorch_v2/configs/e2e_faster_rcnn_R_50_C4_1x_caffe2.yaml

I don't understand what happened, I also want to know where should I put downloaded model and coco datasets, I didn't see in any help documents, byw, I run demo successfully when I put the model in install_dir

**Comment by hheavenknowss** [comment]
Never mind, I found out  where I miss. Now  I can run the code, and I tested on coco-dateset, I got 3 results, bbox.json, coco_result.pth, prediction.pth, I want to know if there any results I can use to submit to coco's website so I can see the test result on test-dev, thanks.

**Comment by tomorrow1210** [comment]
@hheavenknowss I meet the same problem as https://github.com/tianzhi0549/FCOS/issues/137#issue-491731004， how did you solve it?

**Comment by tianzhi0549** [comment]
@tomorrow1210 it seems that you did not specify --config-file in your command line.

**Comment by tomorrow1210** [comment]
@tianzhi0549 I have solved this problem, it was incomplete installation of cocoapi or fcos. See as https://github.com/tianzhi0549/FCOS/blob/master/INSTALL.md
