### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by YYZ-rose** [tianzhi0549/FCOS#144]
ze@node2:~/mmdetection$ CUDA_VISIBLE_DEVICES=1 python tools/train.py configs/fcos/fcos_mstrain_640_800_x101_64x4d_fpn_gn_2x.py
Traceback (most recent call last):
  File "tools/train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
  File "/home/ze/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/ze/mmdetection/mmdet/apis/inference.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/home/ze/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "/home/ze/anaconda3/lib/python3.6/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/home/ze/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "/home/yangyuze/anaconda3/lib/python3.6/site-packages/matplotlib/path.py", line 21, in <module>
    from . import _path, rcParams
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/ze/anaconda3/lib/python3.6/site-packages/matplotlib/_path.cpython-36m-x86_64-linux-gnu.so)

**Comment by dreamhighchina** [comment]
cuda does not match pytorch version
