### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by fnp0217** [tianzhi0549/FCOS#148]
(fcos) C:\Users\User\INSTALL_DIR\FCOS>python demo/fcos_demo.py
Traceback (most recent call last):
  File "demo/fcos_demo.py", line 6, in <module>
    from predictor import COCODemo
  File "C:\Users\User\INSTALL_DIR\FCOS\demo\predictor.py", line 6, in <module>
    from fcos_core.modeling.detector import build_detection_model
  File "c:\users\user\install_dir\fcos\fcos_core\modeling\detector\__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "c:\users\user\install_dir\fcos\fcos_core\modeling\detector\detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "c:\users\user\install_dir\fcos\fcos_core\modeling\detector\generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "c:\users\user\install_dir\fcos\fcos_core\modeling\backbone\__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "c:\users\user\install_dir\fcos\fcos_core\modeling\backbone\backbone.py", line 7, in <module>
    from fcos_core.modeling.make_layers import conv_with_kaiming_uniform
  File "c:\users\user\install_dir\fcos\fcos_core\modeling\make_layers.py", line 10, in <module>
    from fcos_core.layers import Conv2d
  File "c:\users\user\install_dir\fcos\fcos_core\layers\__init__.py", line 10, in <module>
    from .nms import nms
  File "c:\users\user\install_dir\fcos\fcos_core\layers\nms.py", line 3, in <module>
    from fcos_core import _C
ImportError: DLL load failed: The specified module could not be found.

**Comment by tianzhi0549** [comment]
@fnp0217 Did you follow the installation instruction to install the project correctly?

**Comment by fnp0217** [comment]
i did, had to make minor adjustments as cocoapi isn't supported in windows , i did install it successfully so it should t be an issue.

**Comment by tianzhi0549** [comment]
@fnp0217 Great!

**Comment by July-chat** [comment]
how to solve
