### ISSUE TITLE
Default process group is not initialized

### ISSUE THREAD

**Issue by GuoWei2019** [tianzhi0549/FCOS#156]
warnings.warn("torch.distributed.reduce_op is deprecated, please use "
Traceback (most recent call last):
  File "tools/train_net.py", line 180, in <module>
    main()
  File "tools/train_net.py", line 173, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 79, in train
    arguments,
  File "/FCOS/fcos_core/engine/trainer.py", line 69, in do_train
    loss_dict = model(images, targets)
  File "/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/FCOS/fcos_core/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/FCOS/fcos_core/modeling/rpn/fcos/fcos.py", line 159, in forward
    centerness, targets
  File "/FCOS/fcos_core/modeling/rpn/fcos/fcos.py", line 169, in _forward_train
    locations, box_cls, box_regression, centerness, targets
  File "/FCOS/fcos_core/modeling/rpn/fcos/loss.py", line 282, in __call__
    reduce_sum(centerness_flatten.new_tensor([0.0]))
  File "/FCOS/fcos_core/modeling/rpn/fcos/loss.py", line 29, in reduce_sum
    dist.all_reduce(tensor, op=dist.reduce_op.SUM)
  File "/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 899, in all_reduce
    _check_default_pg()
  File "/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 191, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized

**Comment by tianzhi0549** [comment]
@GuoWei2019 sorry, it is a bug and has been fixed in the latest commit.

**Comment by Jilliansea** [comment]
@tianzhi0549  I conter the same question. I clone this code yesterday, and run train with only 1 gpu, and run commonds as follows:
'python -m torch.distributed.launch --nproc_per_node=1 --master_port=$((RANDOM + 10000)) tools/train_net.py --config-file configs/fcos/fcos_syncbn_bs32_c128_MNV2_FPN_1x.yaml DATALOADER.NUM_WORKERS 2 OUTPUT_DIR training_dir/fcos_syncbn_bs32_c128_MNV2_FPN_1x'
