### ISSUE TITLE
FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by codylcs** [tianzhi0549/FCOS#161]
when running fcos_demo.py ,questions happend as flowing:

piled with GPU support (nms at fcos_core/csrc/nms.h:22)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f03c2ace441 in /home/cody/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f03c2acdd7a in /home/cody/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: nms(at::Tensor const&, at::Tensor const&, float) + 0xd4 (0x7f03beaff524 in /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x17296 (0x7f03beb0d296 in /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x1732e (0x7f03beb0d32e in /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x146ca (0x7f03beb0a6ca in /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>

**Comment by codylcs** [comment]
https://github.com/tianzhi0549/FCOS/issues/160

**Comment by tianzhi0549** [comment]
@codylcs The error information you posted here is incomplete.

**Comment by codylcs** [comment]
the question now is that:
/home/cody/anaconda3/envs/FCOS/bin/python /home/cody/PycharmProjects/FCOS/FCOS-master/demo/fcos_demo.py
Traceback (most recent call last):
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/demo/fcos_demo.py", line 6, in <module>
    from predictor import COCODemo
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/demo/predictor.py", line 6, in <module>
    from fcos_core.modeling.detector import build_detection_model
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/backbone/backbone.py", line 7, in <module>
    from fcos_core.modeling.make_layers import conv_with_kaiming_uniform
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/make_layers.py", line 10, in <module>
    from fcos_core.layers import Conv2d
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/layers/nms.py", line 3, in <module>
    from fcos_core import _C
ImportError: /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE

Process finished with exit code 1

**Comment by codylcs** [comment]
when torchvisio is changed as version=1.1.0 ,the question happened again:
/home/cody/anaconda3/envs/FCOS/bin/python /home/cody/PycharmProjects/FCOS/FCOS-master/demo/fcos_demo.py
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/demo/fcos_demo.py", line 109, in <module>
    main()
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/demo/fcos_demo.py", line 101, in main
    composite = coco_demo.run_on_opencv_image(img)
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/demo/predictor.py", line 172, in run_on_opencv_image
    predictions = self.compute_prediction(image)
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/demo/predictor.py", line 205, in compute_prediction
    predictions = self.model(image_list)
  File "/home/cody/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/cody/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/rpn/fcos/fcos.py", line 164, in forward
    centerness, images.image_sizes
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/rpn/fcos/fcos.py", line 181, in _forward_test
    centerness, image_sizes
  File "/home/cody/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/rpn/fcos/inference.py", line 137, in forward
    boxlists = self.select_over_all_levels(boxlists)
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/modeling/rpn/fcos/inference.py", line 164, in select_over_all_levels
    score_field="scores"
  File "/home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/structures/boxlist_ops.py", line 27, in boxlist_nms
    keep = _box_nms(boxes, score, nms_thresh)
RuntimeError: Not compiled with GPU support (nms at fcos_core/csrc/nms.h:22)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fa273c6f441 in /home/cody/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fa273c6ed7a in /home/cody/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: nms(at::Tensor const&, at::Tensor const&, float) + 0xd4 (0x7fa270227524 in /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x17296 (0x7fa270235296 in /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x1732e (0x7fa27023532e in /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x146ca (0x7fa2702326ca in /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>

**Comment by Shuai-Xie** [comment]
I got the same question and I don't know what to do...

**error:**
```
$ python demo/fcos_demo.py 
Traceback (most recent call last):
  File "demo/fcos_demo.py", line 6, in <module>
    from predictor import COCODemo
  File "/disk1/xs/detect/FCOS/demo/predictor.py", line 6, in <module>
    from fcos_core.modeling.detector import build_detection_model
  File "/disk1/xs/detect/FCOS/fcos_core/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/disk1/xs/detect/FCOS/fcos_core/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/disk1/xs/detect/FCOS/fcos_core/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/disk1/xs/detect/FCOS/fcos_core/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/disk1/xs/detect/FCOS/fcos_core/modeling/backbone/backbone.py", line 7, in <module>
    from fcos_core.modeling.make_layers import conv_with_kaiming_uniform
  File "/disk1/xs/detect/FCOS/fcos_core/modeling/make_layers.py", line 10, in <module>
    from fcos_core.layers import Conv2d
  File "/disk1/xs/detect/FCOS/fcos_core/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/disk1/xs/detect/FCOS/fcos_core/layers/nms.py", line 3, in <module>
    from fcos_core import _C
ImportError: /disk1/xs/detect/FCOS/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd
```

**env:**
```
$ pip list
Package         Version     Location             
--------------- ----------- ---------------------
certifi         2019.9.11   
cpools          0.0.0       
cycler          0.10.0      
Cython          0.29.13     
decorator       4.4.0       
fcos            0.1.9       /disk1/xs/detect/FCOS
imageio         2.6.1       
kiwisolver      1.1.0       
matplotlib      3.1.1       
networkx        2.3         
ninja           1.9.0.post1 
numpy           1.17.2      
opencv-python   4.1.1.26    
Pillow          6.2.0       
pip             19.2.3      
pycocotools     2.0.0       
pyparsing       2.4.2       
python-dateutil 2.8.0       
PyWavelets      1.0.3       
PyYAML          5.1.2       
scikit-image    0.15.0      
scipy           1.3.1       
setuptools      41.4.0      
six             1.12.0      
torch           1.1.0       
torchvision     0.2.1       
tqdm            4.36.1      
wheel           0.33.6      
yacs            0.1.6     
```

**Comment by Shuai-Xie** [comment]
I have solved this problem.

**torch 1.0.0 + torchvision 0.2.1 + cudatoolkit 9.0 / 10.0**

before, I forget to *use conda to install cudatoolkit**, which is necessary to build `fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)`

My env：
```
$ conda list
# packages in environment at /disk1/xs/anaconda3/envs/fcos:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2019.8.28                     0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2019.9.11                py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudatoolkit               9.0                  h13b8566_0    <unknown>
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.13                  pypi_0    pypi
decorator                 4.4.0                    pypi_0    pypi
fcos                      0.1.9                     dev_0    <develop>
imageio                   2.6.1                    pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.2.1                hd88cf55_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib                3.1.1                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
networkx                  2.3                      pypi_0    pypi
ninja                     1.9.0.post1              pypi_0    pypi
numpy                     1.17.2                   pypi_0    pypi
opencv-python             4.1.1.26                 pypi_0    pypi
openssl                   1.1.1d               h7b6447c_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pillow                    6.2.0                    pypi_0    pypi
pip                       19.2.3                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pycocotools               2.0.0                    pypi_0    pypi
pyparsing                 2.4.2                    pypi_0    pypi
python                    3.6.9                h265db76_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.0                    pypi_0    pypi
pywavelets                1.0.3                    pypi_0    pypi
pyyaml                    5.1.2                    pypi_0    pypi
readline                  7.0                  h7b6447c_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scikit-image              0.15.0                   pypi_0    pypi
scipy                     1.3.1                    pypi_0    pypi
setuptools                41.4.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.12.0                   pypi_0    pypi
sqlite                    3.30.0               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tk                        8.6.8                hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torch                     1.0.0                    pypi_0    pypi
torchvision               0.2.1                    pypi_0    pypi
tqdm                      4.36.1                   pypi_0    pypi
wheel                     0.33.6                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.4                h14c3975_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yacs                      0.1.6                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
```

**Comment by codylcs** [comment]
thank,but question still here:
(/home/cody/anaconda3/envs/FCOS) cody@codylcs:~/PycharmProjects/FCOS/FCOS-master$ conda list
# packages in environment at /home/cody/anaconda3/envs/FCOS:
#
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_pytorch_select           0.2                       gpu_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
certifi                   2016.2.28                py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cffi                      1.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cudatoolkit               10.0.130                      0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                    <pip>
Cython                    0.29.13                   <pip>
decorator                 4.4.0                     <pip>
freetype                  2.5.5                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
imageio                   2.5.0                     <pip>
intel-openmp              2019.4                      243    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jbig                      2.1                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
kiwisolver                1.1.0                     <pip>
libffi                    3.2.1                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgcc-ng                 9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgfortran-ng            7.3.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.30                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libstdcxx-ng              9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtiff                   4.0.6                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
matplotlib                3.1.1                     <pip>
mkl                       2019.4                      243    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py36he904b0f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.0.14           py36ha843d7b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.1.0            py36hd6b4f25_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
networkx                  2.3                       <pip>
ninja                     1.7.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ninja                     1.9.0.post1               <pip>
numpy                     1.17.2           py36haad9e8e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.17.2           py36hde5b4d6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
olefile                   0.44                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
opencv-python             4.1.1.26                  <pip>
openssl                   1.0.2l                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
Pillow                    6.2.0                     <pip>
pillow                    4.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pip                       9.0.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pycocotools               2.0                       <pip>
pycparser                 2.18                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyparsing                 2.4.2                     <pip>
python                    3.6.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-dateutil           2.8.0                     <pip>
pytorch                   1.3.0           py3.6_cuda10.0.130_cudnn7.6.3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
PyWavelets                1.0.3                     <pip>
PyYAML                    5.1.2                     <pip>
readline                  6.2                           2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scikit-image              0.15.0                    <pip>
scipy                     1.3.1                     <pip>
setuptools                36.4.0                   py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
six                       1.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
some-package              0.1                       <pip>
sqlite                    3.13.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tk                        8.5.18                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
torch                     1.0.0                     <pip>
torchvision               0.2.1                      py_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
tqdm                      4.19.9                    <pip>
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xz                        5.2.3                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
yacs                      0.1.6                     <pip>
zlib                      1.2.11                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
