### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by 1005673201** [tianzhi0549/FCOS#172]
The training dataset is coco_train_2017.
My train command is CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port=10001 tools/train_net.py --config-file fcos_R_50_FPN_1x.yaml DATALOADER.NUM_WORKERS 2
Is there problem?
And, the error is:

loading annotations into memory...
Done (t=19.15s)
creating index...
index created!
2019-10-14 12:10:04,917 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 180, in <module>
    main()
  File "tools/train_net.py", line 173, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 79, in train
    arguments,
  File "/home/r/FCOS_PLUS/maskrcnn_benchmark/engine/trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/r/FCOS_PLUS/maskrcnn_benchmark/data/datasets/coco.py", line 91, in __getitem__
    target = target.clip_to_image(remove_empty=True)
  File "/home/r/FCOS_PLUS/maskrcnn_benchmark/structures/bounding_box.py", line 223, in clip_to_image
    return self[keep]
  File "/home/r/FCOS_PLUS/maskrcnn_benchmark/structures/bounding_box.py", line 208, in __getitem__
    bbox.add_field(k, v[item])
  File "/home/r/FCOS_PLUS/maskrcnn_benchmark/structures/segmentation_mask.py", line 513, in __getitem__
    selected_instances = self.instances.__getitem__(item)
  File "/home/r/FCOS_PLUS/maskrcnn_benchmark/structures/segmentation_mask.py", line 422, in __getitem__
    selected_polygons.append(self.polygons[i])
IndexError: list index out of range

Traceback (most recent call last):
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/r/anaconda3/envs/FCOS/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/r/anaconda3/envs/FCOS/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'fcos_R_50_FPN_1x.yaml', 'DATALOADER.NUM_WORKERS', '2']' returned non-zero exit status 1.

**Comment by WangZhaoxue** [comment]
the same issue
