### ISSUE TITLE
ImportError: /install_caffe/anaconda2/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found 

### ISSUE THREAD

**Issue by reedwiththought** [tianzhi0549/FCOS#186]
hi tianzhi0549, I run :
python tools/test_net.py \
>     --config-file configs/fcos/fcos_imprv_R_50_FPN_1x.yaml \
>     MODEL.WEIGHT FCOS_imprv_R_50_FPN_1x.pth \
>     TEST.IMS_PER_BATCH 4

but got:
Traceback (most recent call last):
  File "tools/test_net.py", line 11, in <module>
    from fcos_core.data import make_data_loader
  File "/home/wys/lucky/FCOS/fcos_core/data/__init__.py", line 1, in <module>
    from fcos_core.data import datasets
  File "/home/wys/lucky/FCOS/fcos_core/data/datasets/__init__.py", line 3, in <module>
    from .coco import coco_evaluation
  File "/home/wys/lucky/FCOS/fcos_core/data/datasets/coco.py", line 6, in <module>
    from fcos_core.structures.segmentation_mask import SegmentationMask
  File "/home/wys/lucky/FCOS/fcos_core/structures/segmentation_mask.py", line 5, in <module>
    from fcos_core.layers.misc import interpolate
  File "/home/wys/lucky/FCOS/fcos_core/layers/__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "/home/wys/lucky/FCOS/fcos_core/layers/nms.py", line 3, in <module>
    from fcos_core import _C
ImportError: /install_caffe/anaconda2/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/wys/lucky/FCOS/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so)

@tianzhi0549 
Could you help me ? Thank you.

**Comment by Damilytutu** [comment]
you can add LD_LIBRARY_PATH=/usr/local/lib64/ before command python xxx

**Comment by reedwiththought** [comment]
OK, Thank you!
