### ISSUE TITLE
environment problem

### ISSUE THREAD

**Issue by MsRabbits** [tianzhi0549/FCOS#195]
Does this version of code support win10?Or just support linux?

**Comment by tianzhi0549** [comment]
@MsRabbits Running it on Windows should be OK. FCOS is written by python and built on PyTorch, so it is platform-independent.

**Comment by MsRabbits** [comment]
> @MsRabbits Running it on Windows should be OK. FCOS is written by python and built on PyTorch, so it is platform-independent.

Thx for your reply. Another problem come out,hope for your advice.
After the Installation, I run the code 'python demo/fcos_demo.py',and there are somethin wrong:
(tree) F:\somecoders\FCOS-master>python demo/fcos_demo.py
Traceback (most recent call last):
  File "demo/fcos_demo.py", line 6, in <module>
    from demo.predictor import COCODemo
  File "f:\somecoders\fcos-master\demo\predictor.py", line 6, in <module>
    from fcos_core.modeling.detector import build_detection_model
  File "f:\somecoders\fcos-master\fcos_core\modeling\detector\__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "f:\somecoders\fcos-master\fcos_core\modeling\detector\detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "f:\somecoders\fcos-master\fcos_core\modeling\detector\generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "f:\somecoders\fcos-master\fcos_core\modeling\backbone\__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "f:\somecoders\fcos-master\fcos_core\modeling\backbone\backbone.py", line 7, in <module>
    from fcos_core.modeling.make_layers import conv_with_kaiming_uniform
  File "f:\somecoders\fcos-master\fcos_core\modeling\make_layers.py", line 10, in <module>
    from fcos_core.layers import Conv2d
  File "f:\somecoders\fcos-master\fcos_core\layers\__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "f:\somecoders\fcos-master\fcos_core\layers\nms.py", line 3, in <module>
    from fcos_core import _C
ImportError: DLL load failed: 找不到指定的模块。

**Comment by MsRabbits** [comment]
But i have got this file after compile, does this ‘_c'file is not correct, or it cannot work for win10?
_C.cp37-win_amd64.pyd

**Comment by MsRabbits** [comment]
when i run the python setup.py build develop --no-deps, i got this:
(tree) F:\somecoders\FCOS-master>python setup.py build develop --no-deps
running build
running build_py
running egg_info
writing fcos.egg-info\PKG-INFO
writing dependency_links to fcos.egg-info\dependency_links.txt
writing requirements to fcos.egg-info\requires.txt
writing top-level names to fcos.egg-info\top_level.txt
reading manifest file 'fcos.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'fcos\configs'
writing manifest file 'fcos.egg-info\SOURCES.txt'
running build_ext
E:\anaconda\anaconda\envs\tree\lib\site-packages\torch\utils\cpp_extension.py:196: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (cl 19.00.24210) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
running build_scripts
running develop
running build_ext
copying build\lib.win-amd64-3.7\fcos_core\_C.cp37-win_amd64.pyd -> fcos_core
Creating e:\anaconda\anaconda\envs\tree\lib\site-packages\fcos.egg-link (link to .)
fcos 0.1.9 is already the active version in easy-install.pth
Installing fcos script to E:\anaconda\anaconda\envs\tree\Scripts

Installed f:\somecoders\fcos-master

**Comment by fourk-ty** [comment]
Did you try to install it successfully in windows10 finally?

**Comment by cvJie** [comment]
> when i run the python setup.py build develop --no-deps, i got this:
> (tree) F:\somecoders\FCOS-master>python setup.py build develop --no-deps
> running build
> running build_py
> running egg_info
> writing fcos.egg-info\PKG-INFO
> writing dependency_links to fcos.egg-info\dependency_links.txt
> writing requirements to fcos.egg-info\requires.txt
> writing top-level names to fcos.egg-info\top_level.txt
> reading manifest file 'fcos.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no directories found matching 'fcos\configs'
> writing manifest file 'fcos.egg-info\SOURCES.txt'
> running build_ext
> E:\anaconda\anaconda\envs\tree\lib\site-packages\torch\utils\cpp_extension.py:196: UserWarning:
> 
> ```
>                            !! WARNING !!
> ```
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> Your compiler (cl 19.00.24210) may be ABI-incompatible with PyTorch!
> Please use a compiler that is ABI-compatible with GCC 4.9 and above.
> See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
> 
> See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
> for instructions on how to install GCC 4.9 or higher.
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> ```
>                           !! WARNING !!
> ```
> 
> warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
> running build_scripts
> running develop
> running build_ext
> copying build\lib.win-amd64-3.7\fcos_core_C.cp37-win_amd64.pyd -> fcos_core
> Creating e:\anaconda\anaconda\envs\tree\lib\site-packages\fcos.egg-link (link to .)
> fcos 0.1.9 is already the active version in easy-install.pth
> Installing fcos script to E:\anaconda\anaconda\envs\tree\Scripts
> 
> Installed f:\somecoders\fcos-master

https://github.com/tianzhi0549/FCOS/issues

I run follow you ,but failed.
