### ISSUE TITLE
Demo error:No such file or directory: 'FCOS_imprv_R_50_FPN_1x.pth'

### ISSUE THREAD

**Issue by MsRabbits** [tianzhi0549/FCOS#198]
After i run the 'python demo/fcos_demo.py' on win10, i got the error:

(tree) F:\somecoders\FCOS-master>python demo/fcos_demo.py
Traceback (most recent call last):
  File "demo/fcos_demo.py", line 109, in <module>
    main()
  File "demo/fcos_demo.py", line 93, in main
    min_image_size=args.min_image_size
  File "f:\somecoders\fcos-master\demo\predictor.py", line 117, in __init__
    _ = checkpointer.load(cfg.MODEL.WEIGHT)
  File "f:\somecoders\fcos-master\fcos_core\utils\checkpoint.py", line 61, in load
    checkpoint = self._load_file(f)
  File "f:\somecoders\fcos-master\fcos_core\utils\checkpoint.py", line 136, in _load_file
    loaded = super(DetectronCheckpointer, self)._load_file(f)
  File "f:\somecoders\fcos-master\fcos_core\utils\checkpoint.py", line 95, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "E:\anaconda\anaconda\envs\tree\lib\site-packages\torch\serialization.py", line 366, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'FCOS_imprv_R_50_FPN_1x.pth'

can you give me some advice,my environment list are:
_pytorch_select           1.1.0                       cpu    defaults
_tflow_select             2.1.0                       gpu    defaults
absl-py                   0.8.0                    py37_0    defaults
astor                     0.8.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2019.10.16                    0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2019.9.11                py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.13.1           py37h7a1dbc1_0    defaults
colorama                  0.4.1                      py_0    defaults
cudatoolkit               10.0.130                      0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudnn                     7.6.4                cuda10.0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                    <pip>
Cython                    0.29.14                   <pip>
decorator                 4.4.1                      py_0    defaults
easydict                  1.9                       <pip>
fcos                      0.1.9                     <pip>
freetype                  2.9.1                ha9979f8_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gast                      0.3.2                      py_0    defaults
grpcio                    1.12.1           py37h1a1b453_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
h5py                      2.9.0            py37h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
intel-openmp              2019.4                      245    defaults
ipython                   7.9.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
jedi                      0.15.1                   py37_0    defaults
jpeg                      9b                   hb83a4c4_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
keras-applications        1.0.8                      py_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
kiwisolver                1.1.0                     <pip>
libpng                    1.6.37               h2a8f88b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libprotobuf               3.9.2                h7bd577a_0    defaults
libtiff                   4.0.10               hb898794_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
markdown                  3.1.1                    py37_0    defaults
matplotlib                3.1.1                     <pip>
mkl                       2019.4                      245    defaults
mkl-service               2.3.0            py37hb782905_0    defaults
mkl_fft                   1.0.14           py37h14836fe_0    defaults
mkl_random                1.1.0            py37h675688f_0    defaults
ninja                     1.9.0            py37h74a9793_0    defaults
ninja                     1.9.0.post1               <pip>
numpy                     1.17.2           py37hc73f44b_0    defaults
numpy-base                1.17.2           py37hc3f5095_0    defaults
olefile                   0.46                     py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opencv-python             3.4.2.16                  <pip>
openssl                   1.0.1k                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pandas                    0.25.3                    <pip>
parso                     0.5.1                      py_0    defaults
pickleshare               0.7.5                    py37_0    defaults
Pillow                    5.3.0                     <pip>
pillow                    6.2.1            py37hdc69c19_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       19.3.1                   py37_0    defaults
prompt_toolkit            2.0.10                     py_0    defaults
protobuf                  3.9.2            py37h33f27b4_0    defaults
pycocotools               2.0                       <pip>
pycparser                 2.19                     py37_0    defaults
pygments                  2.4.2                      py_0    defaults
pyparsing                 2.4.4                     <pip>
pyreadline                2.1                      py37_1    defaults
python                    3.7.1                h33f27b4_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.1                     <pip>
pytorch                   1.0.1           py3.7_cuda100_cudnn7_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytz                      2019.3                    <pip>
PyYAML                    5.1.2                     <pip>
scipy                     1.3.1            py37h29ff71c_0    defaults
seaborn                   0.9.0                     <pip>
setuptools                41.6.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.30.1               he774522_0    defaults
tensorboard               1.14.0           py37he3c9ec2_0    defaults
tensorflow                1.14.0          gpu_py37h5512b17_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow-base           1.14.0          gpu_py37h55fc52a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow-estimator      1.14.0                     py_0    defaults
tensorflow-gpu            1.14.0               h0d30ee6_0    defaults
termcolor                 1.1.0                    py37_1    defaults
tk                        8.6.8                hfa6e2cd_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torchvision               0.2.1                      py_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
torchvision               0.2.1                     <pip>
tqdm                      4.37.0                    <pip>
traitlets                 4.3.3                    py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
werkzeug                  0.16.0                     py_0    defaults
wget                      3.2                       <pip>
wheel                     0.33.6                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
wrapt                     1.11.2           py37he774522_0    defaults
xz                        5.2.4                h2fa13f4_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yacs                      0.1.6                     <pip>
zlib                      1.2.11               h62dcd97_3    defaults
zstd                      1.3.7                h508b16e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by MartaTintore** [comment]
I have the same issue, did you solve it?
