### ISSUE TITLE
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Eyren** [tianzhi0549/FCOS#202]
My cuda version is 9.0,pytorch version is 1.1.0,torchvision version is 0.2.1.When i was **python setup.py build develop --no-deps**,it installed sucessfully.But when i ran the demo.py:
```
Traceback (most recent call last):
  File "demo/fcos_demo.py", line 6, in <module>
    from predictor import COCODemo
  File "/home/jjm/FCOS/demo/predictor.py", line 6, in <module>
    from fcos_core.modeling.detector import build_detection_model
  File "/home/jjm/FCOS/fcos_core/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/jjm/FCOS/fcos_core/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/jjm/FCOS/fcos_core/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/home/jjm/FCOS/fcos_core/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/home/jjm/FCOS/fcos_core/modeling/backbone/backbone.py", line 7, in <module>
    from fcos_core.modeling.make_layers import conv_with_kaiming_uniform
  File "/home/jjm/FCOS/fcos_core/modeling/make_layers.py", line 10, in <module>
    from fcos_core.layers import Conv2d
  File "/home/jjm/FCOS/fcos_core/layers/__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "/home/jjm/FCOS/fcos_core/layers/nms.py", line 3, in <module>
    from fcos_core import _C
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```
Can anybody help me?Thank you.

**Comment by Eyren** [comment]
Then i tried to change cuda version to 10.0,pytorch version to 1.2.0,torchvision still 0.2.1,it's also installed FCOS successfully,but when i ran the demo.py:
```
Traceback (most recent call last):
  File "demo/fcos_demo.py", line 6, in <module>
    from predictor import COCODemo
  File "/home/jjm/FCOS/demo/predictor.py", line 6, in <module>
    from fcos_core.modeling.detector import build_detection_model
  File "/home/jjm/FCOS/fcos_core/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/jjm/FCOS/fcos_core/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/jjm/FCOS/fcos_core/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/home/jjm/FCOS/fcos_core/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/home/jjm/FCOS/fcos_core/modeling/backbone/backbone.py", line 7, in <module>
    from fcos_core.modeling.make_layers import conv_with_kaiming_uniform
  File "/home/jjm/FCOS/fcos_core/modeling/make_layers.py", line 10, in <module>
    from fcos_core.layers import Conv2d
  File "/home/jjm/FCOS/fcos_core/layers/__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "/home/jjm/FCOS/fcos_core/layers/nms.py", line 3, in <module>
    from fcos_core import _C
ImportError: /home/jjm/FCOS/fcos_core/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at11ATenOpTable11reportErrorEN3c1012TensorTypeIdE
```

**Comment by tianzhi0549** [comment]
@Eyren Please re-compile the project as you have changed your PyTorch version.

**Comment by Eyren** [comment]
> @Eyren Please re-compile the project as you have changed your PyTorch version.

I did and it's doesn't work.It's also the same error.

**Comment by tianzhi0549** [comment]
@Eyren I suggest you clone the project again because some cached files might exist.

**Comment by Eyren** [comment]
> @Eyren I suggest you clone the project again because some cached files might exist.

Thank you very much!!!!!!!!!It worked!

**Comment by cqu20160901** [comment]
hello, i met the same error, could i delete the cached files so this errors would not happen again? and which files are the cached files?
just clone the projects again seems not a good choice.
