### ISSUE TITLE
OSError: image file is truncated (7 bytes not processed)

### ISSUE THREAD

**Issue by jszgz** [tianzhi0549/FCOS#206]
Traceback (most recent call last):
  File "tools/train_net.py", line 184, in <module>
    main()
  File "tools/train_net.py", line 177, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 83, in train
    arguments,
  File "/home/wt/PycharmProjects/FCOS/fcos_core/engine/trainer.py", line 65, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/root1root/anaconda3/envs/wtFCOS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/root1root/anaconda3/envs/wtFCOS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
OSError: Traceback (most recent call last):
  File "/home/root1root/anaconda3/envs/wtFCOS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/root1root/anaconda3/envs/wtFCOS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/root1root/anaconda3/envs/wtFCOS/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 81, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/wt/PycharmProjects/FCOS/fcos_core/data/datasets/coco.py", line 67, in __getitem__
    img, anno = super(COCODataset, self).__getitem__(idx)
  File "/home/root1root/anaconda3/envs/wtFCOS/lib/python3.6/site-packages/torchvision/datasets/coco.py", line 117, in __getitem__
    img = Image.open(os.path.join(self.root, path)).convert('RGB')
  File "/home/root1root/anaconda3/envs/wtFCOS/lib/python3.6/site-packages/PIL/Image.py", line 930, in convert
    self.load()
  File "/home/root1root/anaconda3/envs/wtFCOS/lib/python3.6/site-packages/PIL/ImageFile.py", line 249, in load
    "(%d bytes not processed)" % len(b)
OSError: image file is truncated (7 bytes not processed)

**Comment by huxiaopeng123** [comment]
I have the same problem as you，have you solved your problem?
