### ISSUE TITLE
when i use the test_net.py to eval the model, an error happen

### ISSUE THREAD

**Issue by houweidong** [tianzhi0549/FCOS#26]
```
Traceback (most recent call last):
  File "/root/models/FCOS/tools/test_net.py", line 97, in <module>
    main()
  File "/root/models/FCOS/tools/test_net.py", line 91, in main
    output_folder=output_folder,
  File "/root/models/FCOS/maskrcnn_benchmark/engine/inference.py", line 115, in inference
    **extra_args)
  File "/root/models/FCOS/maskrcnn_benchmark/data/datasets/evaluation/__init__.py", line 22, in evaluate
    return coco_evaluation(**args)
  File "/root/models/FCOS/maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py", line 20, in coco_evaluation
    expected_results_sigma_tol=expected_results_sigma_tol,
  File "/root/models/FCOS/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 31, in do_coco_evaluation
    predictions, dataset, area=area, limit=limit
  File "/root/models/FCOS/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 233, in evaluate_box_proposals
    inds = prediction.get_field("objectness").sort(descending=True)[1]
  File "/root/models/FCOS/maskrcnn_benchmark/structures/bounding_box.py", line 43, in get_field
    return self.extra_fields[field]
KeyError: 'objectness'
2019-05-02 14:26:22,496 maskrcnn_benchmark.inference INFO: Evaluating bbox proposals

```

boxlist dosn't has the objecness field,  but the coco_eval.py use it to produce results, how can i solve the problem?
if i just alter the "objectness" to "scores", is the eval result right?

**Comment by liuliu66** [comment]
@houweidong hi, I met the same issue as yours. what's the problem about it?

**Comment by aliceyayunji** [comment]
how to correct it ?

**Comment by tianzhi0549** [comment]
@aliceyayunji Are you using the latest code?

**Comment by aliceyayunji** [comment]
I use the benchmark_maskrcnn and merge the change of fcos into it, cannot find any clue.

**Comment by aliceyayunji** [comment]
@tianzhi0549  I use the latest FAIR benchmark_maskrcnn and latest FCOS, the training is ok, any idea which file cause the problem ?

**Comment by tianzhi0549** [comment]
@aliceyayunji Did you merge this line?https://github.com/tianzhi0549/FCOS/blob/620022322423eac84febde920ee5861fe4b9609f/tools/test_net.py#L87

**Comment by aliceyayunji** [comment]
Yes!!! I forgot to merge this line, now everything is OK, thanks a lot.  @tianzhi0549

**Comment by tianzhi0549** [comment]
@aliceyayunji Happy to know it has been solved.
