### ISSUE TITLE
RuntimeError: Not compiled with GPU support (ml_nms at fcos_core/csrc/ml_nms.h:23)

### ISSUE THREAD

**Issue by Adnan-annan** [tianzhi0549/FCOS#297]
Traceback (most recent call last):
  File "tools/test_net.py", line 97, in <module>
    main()
  File "tools/test_net.py", line 82, in main
    inference(
  File "/home/adnan/Documents/FCOS-master/fcos_core/engine/inference.py", line 83, in inference
    predictions = compute_on_dataset(model, data_loader, device, inference_timer)
  File "/home/adnan/Documents/FCOS-master/fcos_core/engine/inference.py", line 30, in compute_on_dataset
    output = model(images.to(device))
  File "/home/adnan/anaconda3/envs/FCOS-master/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/adnan/Documents/FCOS-master/fcos_core/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/adnan/anaconda3/envs/FCOS-master/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/adnan/Documents/FCOS-master/fcos_core/modeling/rpn/fcos/fcos.py", line 162, in forward
    return self._forward_test(
  File "/home/adnan/Documents/FCOS-master/fcos_core/modeling/rpn/fcos/fcos.py", line 179, in _forward_test
    boxes = self.box_selector_test(
  File "/home/adnan/anaconda3/envs/FCOS-master/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/adnan/Documents/FCOS-master/fcos_core/modeling/rpn/fcos/inference.py", line 137, in forward
    boxlists = self.select_over_all_levels(boxlists)
  File "/home/adnan/Documents/FCOS-master/fcos_core/modeling/rpn/fcos/inference.py", line 150, in select_over_all_levels
    result = boxlist_ml_nms(boxlists[i], self.nms_thresh)
  File "/home/adnan/Documents/FCOS-master/fcos_core/structures/boxlist_ops.py", line 55, in boxlist_ml_nms
    keep = _box_ml_nms(boxes, scores, labels.float(), nms_thresh)
RuntimeError: Not compiled with GPU support (ml_nms at fcos_core/csrc/ml_nms.h:23)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f29dd03a193 in /home/adnan/anaconda3/envs/FCOS-master/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: ml_nms(at::Tensor const&, at::Tensor const&, at::Tensor const&, float) + 0x218 (0x7f29d1133ba8 in /home/adnan/Documents/FCOS-master/fcos_core/_C.cpython-38-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x1e532 (0x7f29d1144532 in /home/adnan/Documents/FCOS-master/fcos_core/_C.cpython-38-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x1a9e1 (0x7f29d11409e1 in /home/adnan/Documents/FCOS-master/fcos_core/_C.cpython-38-x86_64-linux-gnu.so)
<omitting python frames>
frame #63: __libc_start_main + 0xe7 (0x7f2a38972b97 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by MartaTintore** [comment]
I am getting the same error...

**Comment by Adnan-annan** [comment]
try installing the pytorch again,, possibly you havnt installed nvidia cuda toolkit before installing pytorch gpu. hope that helps.

**Comment by zhoujingyu13687306871** [comment]
@Adnan-annan @MartaTintore 
If you compiled on the login node of cluster, but login node does not have a GPU device and  not loaded cuda, then this error will be reported. So a GPU device and load cuda  could compiled success.
