### ISSUE TITLE
Can not download the pre-trained model

### ISSUE THREAD

**Issue by ZhengMengbin** [tianzhi0549/FCOS#35]
When I run train.py to train FCOS_X_101_64x4d_FPN_2x, but it happens download error:
`
Downloading: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/20171220/X-101-64x4d.pkl" to /home/zhengchenbin/.torch/models/X-101-64x4d.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 175, in <module>
    main()
  File "tools/train_net.py", line 168, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 54, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 65, in load
    checkpoint = self._load_file(f)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 133, in _load_file
    cached_f = cache_url(f)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/utils/model_zoo.py", line 54, in cache_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/utils/model_zoo.py", line 76, in _download_url_to_file
    u = urlopen(url)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
`
Can you provide  the pre-trained model X-101-64x4d.pkl or give another download link such as baiduyun or google drive? Thank you very much!

**Comment by tianzhi0549** [comment]
@ZhengMengbin Please download the model here https://cloudstor.aarnet.edu.au/plus/s/k3ys35075jmU1RP/download.

**Comment by ZhengMengbin** [comment]
I use the pre-trained model from https://cloudstor.aarnet.edu.au/plus/s/k3ys35075jmU1RP/download, but it happens an another error:
  'File "tools/train_net.py", line 175, in <module>
    main()
  File "tools/train_net.py", line 168, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 54, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 65, in load
    checkpoint = self._load_file(f)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/utils/checkpoint.py", line 138, in _load_file
    return load_c2_format(self.cfg, f)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/utils/c2_model_loading.py", line 175, in load_c2_format
    return C2_FORMAT_LOADER[cfg.MODEL.BACKBONE.CONV_BODY](cfg, f)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/utils/c2_model_loading.py", line 170, in load_resnet_c2_format
    state_dict = _rename_weights_for_resnet(state_dict, stages)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/utils/c2_model_loading.py", line 124, in _rename_weights_for_resnet
    w = torch.from_numpy(v)
TypeError: expected np.ndarray (got str)'
It seems this pre-trained model do not the same model from https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/20171220/X-101-64x4d.pkl.

**Comment by tianzhi0549** [comment]
@ZhengMengbin Please add the following code
```
if 'weight_order' in k:
    continue
```
to https://github.com/tianzhi0549/FCOS/blob/c51436a609229f5174185269c5ef27cf84ea881b/maskrcnn_benchmark/utils/c2_model_loading.py#L122.
It will skip the key `weight_order`.

**Comment by ZhengMengbin** [comment]
It works, thank you very much for your reply! I will close this issue.

**Comment by ZhengMengbin** [comment]
I have another question, I download the trained model FCOS_X_101_64x4d_FPN_2x, its size is only 361.5M, but I use the pre-trained model from https://cloudstor.aarnet.edu.au/plus/s/k3ys35075jmU1RP/download(the pre-trained model's size is 667.7M), the saved model's size is 687M, why is the size gap so large?
![image](https://user-images.githubusercontent.com/26650043/57759257-2b494800-772c-11e9-9da7-60e817e62189.png)
![image](https://user-images.githubusercontent.com/26650043/57759650-f1c50c80-772c-11e9-92fc-4372609919d0.png)

**Comment by tianzhi0549** [comment]
@ZhengMengbin We remove all solver states for our released models.

**Comment by ZhengMengbin** [comment]
Is it convenient to provide a script file for removing all the solver states?

**Comment by tianzhi0549** [comment]
@ZhengMengbin We will add the script into our code when we have time. For now, you can use `torch.load` load the model and then delete what you don't want. Next, you can use `torch.save` to save the pruned model.

**Comment by ZhengMengbin** [comment]
OK, special thanks, I will try it.

**Comment by ZhengMengbin** [comment]
I use the code as follows to remove all the solver states：
`
import torch

model_path = '/FCOS/model_0022500.pth'
model_state_dict = torch.load(model_path)

from collections import OrderedDict
new_state_dict = OrderedDict()

# model_state_dict has four items: optimizer, scheduler, model and iteration
# We only keep model and iteration
for k, v in model_state_dict.items():
    print(k)
    if k == 'model' or k == 'iteration':
        new_state_dict[k] = v

torch.save(new_state_dict, '/models/model_0022500.pth')
`
Using the above code, I got the same model size as the author.

**Comment by tianzhi0549** [comment]
@ZhengMengbin Thank you very much for posting it.
