### ISSUE TITLE
Deepcopy returns TypeError: 'int' object is not callable

### ISSUE THREAD

**Issue by taokunade-gt** [tianzhi0549/FCOS#388]
Running demo/fcos_demo.py returns the error message below:

(fcos) C:\Users\Okunade\Desktop\MYFOLDERS\Ph.D\PROG\FCOS-master\fcos>python demo/fcos_demo.py
Traceback (most recent call last):
  File "C:\Users\Okunade\Desktop\MYFOLDERS\Ph.D\PROG\FCOS-master\fcos\demo\fcos_demo.py", line 118, in <module>
    main()
  File "C:\Users\Okunade\Desktop\MYFOLDERS\Ph.D\PROG\FCOS-master\fcos\demo\fcos_demo.py", line 57, in main
    cfg.merge_from_file(args.config_file)
  File "C:\Users\Okunade\anaconda3\envs\fcos\lib\site-packages\yacs\config.py", line 223, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "C:\Users\Okunade\anaconda3\envs\fcos\lib\site-packages\yacs\config.py", line 227, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "C:\Users\Okunade\anaconda3\envs\fcos\lib\site-packages\yacs\config.py", line 478, in _merge_a_into_b
    v = copy.deepcopy(v_)
  File "C:\Users\Okunade\anaconda3\envs\fcos\lib\copy.py", line 155, in deepcopy
    y = copier(memo)
TypeError: 'int' object is not callable

I have not been able to figure out what I am doing wrong.

Please help

**Comment by taokunade-gt** [comment]
Resolved by reinstalling.
