### ISSUE TITLE
runtimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by caffelearn** [tianzhi0549/FCOS#42]
File "d:\pytorch\fcos-master\maskrcnn_benchmark\modeling\rpn\fcos\loss.py", line 99, in compute_targets_for_locations
    is_in_boxes = reg_targets_per_im.min(dim=2)[0] > 0

RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity

**Comment by tianzhi0549** [comment]
@caffelearn It seems that `reg_targets_per_im` has no elements.

**Comment by caffelearn** [comment]
@tianzhi0549 ，it is solved,thanks

**Comment by ZhengMengbin** [comment]
How did you solve it? I trained on other datasets and I also encountered this problem：
Traceback (most recent call last):
  File "tools/train_net.py", line 198, in <module>
    main()
  File "tools/train_net.py", line 190, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 77, in train
    arguments,
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/engine/trainer.py", line 66, in do_train
    loss_dict = model(images, targets)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 357, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/fcos.py", line 134, in forward
    centerness, targets
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/fcos.py", line 144, in _forward_train
    locations, box_cls, box_regression, centerness, targets
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/loss.py", line 146, in __call__
    labels, reg_targets = self.prepare_targets(locations, targets)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/loss.py", line 57, in prepare_targets
    points_all_level, targets, expanded_object_sizes_of_interest
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/loss.py", line 98, in compute_targets_for_locations
    is_in_boxes = reg_targets_per_im.min(dim=2)[0] > 0
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity
