### ISSUE TITLE
RuntimeError?

### ISSUE THREAD

**Issue by ZhengMengbin** [tianzhi0549/FCOS#47]
When I was training on my own dataset, I encountered the following problem：
Traceback (most recent call last):
  File "tools/train_net.py", line 198, in <module>
    main()
  File "tools/train_net.py", line 190, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 77, in train
    arguments,
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/engine/trainer.py", line 66, in do_train
    loss_dict = model(images, targets)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 357, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/zhengchenbin/anaconda3/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/fcos.py", line 134, in forward
    centerness, targets
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/fcos.py", line 144, in _forward_train
    locations, box_cls, box_regression, centerness, targets
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/loss.py", line 146, in __call__
    labels, reg_targets = self.prepare_targets(locations, targets)
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/loss.py", line 57, in prepare_targets
    points_all_level, targets, expanded_object_sizes_of_interest
  File "/home/zhengchenbin/FcosNet/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/loss.py", line 98, in compute_targets_for_locations
    is_in_boxes = reg_targets_per_im.min(dim=2)[0] > 0
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity.
It seems to be reading an image without any ground truth box, but I checked my dataset, all images have ground truth box. And I found that the reading data class COCODataset will automatically ignore images without any box.
Any ideas? How can I solve it?

**Comment by tianzhi0549** [comment]
@ZhengMengbin I suggest that you debug your code line by line to figure out why `reg_targets_per_im` has no elements.

**Comment by ZhengMengbin** [comment]
@tianzhi0549 Thanks, I found the reason why the program reported this error. BoxList class have a function named clip_to_image(), it will check ground truth boxes are inside the image or not. And I print the image path and ground truth boxes, find that the box is outside the image (this box is mislabeled).

**Comment by tianzhi0549** [comment]
@ZhengMengbin Happy to know that.

**Comment by qianzhang2018** [comment]
我遇到了一个和你一样的问题，真实框在图片外面是什么意思，你怎么解决这个bug的～？能解答一下嘛？ @ZhengMengbin

**Comment by ZhengMengbin** [comment]
@qianzhang2018  就是BoxList类中的clip_to_image()函数会检查图像上的所有真实框是不是都整个或部分在图像区域内，如果真实框的四个顶点都在图像区域外，那么该函数就会把这个真实框舍去，如果所有都不在图像区域内（就是真实框都标在图像外面了），就会引发上述错误，即当前图像没有任何有效的真实框

**Comment by qianzhang2018** [comment]
@ZhengMengbin 那也就说你这个错误产生的原因是因为数据集本身的问题?  你最后是把这些标注错误的图像去除？

**Comment by ZhengMengbin** [comment]
@qianzhang2018 是的，你可以检查以下你的数据集是否有图像没有标注框，或者查查FCOS中加载图像的那些代码，定位输出一下是加载到哪张图发生了问题。

**Comment by qianzhang2018** [comment]
@ZhengMengbin 好的，谢谢，非常感谢你了，我定位一下

**Comment by JoernZheng** [comment]
解决了我的问题，谢谢了！
