### ISSUE TITLE
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by guodanying** [tianzhi0549/FCOS#49]
Traceback (most recent call last):
  File "tools/train_net.py", line 176, in <module>
    main()
  File "tools/train_net.py", line 169, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 75, in train
    arguments,
  File "/home/administrator/FCOS/maskrcnn_benchmark/engine/trainer.py", line 66, in do_train
    loss_dict = model(images, targets)
  File "/home/administrator/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/administrator/FCOS/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/administrator/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/administrator/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/fcos.py", line 134, in forward
    centerness, targets
  File "/home/administrator/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/fcos.py", line 144, in _forward_train
    locations, box_cls, box_regression, centerness, targets
  File "/home/administrator/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/loss.py", line 142, in __call__
    labels, reg_targets = self.prepare_targets(locations, targets)
  File "/home/administrator/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/loss.py", line 57, in prepare_targets
    points_all_level, targets, expanded_object_sizes_of_interest
  File "/home/administrator/FCOS/maskrcnn_benchmark/modeling/rpn/fcos/loss.py", line 94, in compute_targets_for_locations
    is_in_boxes = reg_targets_per_im.min(dim=2)[0] > 0
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity

how can i solve it ?

And i train my own data,i have only 20 classes
should i change 80(coco ) to 20 in the network?

**Comment by tianzhi0549** [comment]
@guodanying Sure, you should change 80 to 20.
