### ISSUE TITLE
AttributeError: 'list' object has no attribute 'resize'

### ISSUE THREAD

**Issue by jewelc92** [tianzhi0549/FCOS#50]
When I train on the coco dataset on single GPU,  my datapath is  FCOS-master/datasets/coco, in the coco folder are annotations, train2014 and val2014 folders, in the annotations folder are instances_train2014.json and instances_valminusminival2014.json, and I input "python -m torch.distributed.launch --nproc_per_node=1 --master_port=$((RANDOM + 10000)) tools/train_net.py --skip-test --config-file configs/fcos/fcos_R_50_FPN_1x.yaml DATALOADER.NUM_WORKERS 0 OUTPUT_DIR training_dir/fcos_R_50_FPN_1x",  then I ran into the AttributeError:
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 167, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/cj/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/cj/maskrcnn_benchmark/data/datasets/coco.py", line 67, in __getitem__
    img, anno = super(COCODataset, self).__getitem__(idx)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torchvision-0.2.3a0+9077164-py3.6-linux-x86_64.egg/torchvision/datasets/coco.py", line 114, in __getitem__
  File "/cj/maskrcnn_benchmark/data/transforms/transforms.py", line 15, in __call__
    image, target = t(image, target)
  File "/cj/maskrcnn_benchmark/data/transforms/transforms.py", line 60, in __call__
    target = target.resize(image.size)
AttributeError: 'list' object has no attribute 'resize'
Traceback (most recent call last):
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/miniconda/envs/py36/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--skip-test', '--config-file', 'configs/fcos/fcos_R_50_FPN_1x.yaml', 'DATALOADER.NUM_WORKERS', '0', 'OUTPUT_DIR', 'training_dir/fcos_R_50_FPN_1x']' returned non-zero exit status 1.

What should I do?

**Comment by tianzhi0549** [comment]
@jewelc92 Did you change any of the codes?

**Comment by jewelc92** [comment]
> @jewelc92 Did you change any of the codes?

No, I did not make any change on the codes.

**Comment by jewelc92** [comment]
I ran the codes in docker, and ran the demo/focos_demo.py successfully, is there any possibility that some wrong with the docker?

**Comment by tianzhi0549** [comment]
@jewelc92 I do not know if the error is related to docker. But I notice that you are using a different version of torchvision with us. Can you try to use torchvision==0.2.1 instead?

**Comment by EDG-Zola** [comment]
@tianzhi0549 
I solved the same problem by your method
```bash
# uninstall torchvision already installed
pip uninstall torchvision
# install torchvision==0.2.1
pip install torchvision==0.2.1 
```

**Comment by tianzhi0549** [comment]
@EDG-Zola Thank you for posting it!

**Comment by jewelc92** [comment]
I solve the problem too by replacing the torchvision version, thank you very much

**Comment by tomorrow1210** [comment]
I solve the problem too by replacing the torchvision version, thank you very much
