### ISSUE TITLE
error about  /FCOS/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by studyharderer** [tianzhi0549/FCOS#69]
Traceback (most recent call last):
  File "demo/fcos_demo.py", line 6, in <module>
    from predictor import COCODemo
  File "/home/yong/FCOS/FCOS/demo/predictor.py", line 6, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "/home/yong/FCOS/FCOS/maskrcnn_benchmark/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/yong/FCOS/FCOS/maskrcnn_benchmark/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/yong/FCOS/FCOS/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/home/yong/FCOS/FCOS/maskrcnn_benchmark/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/home/yong/FCOS/FCOS/maskrcnn_benchmark/modeling/backbone/backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "/home/yong/FCOS/FCOS/maskrcnn_benchmark/modeling/make_layers.py", line 10, in <module>
    from maskrcnn_benchmark.layers import Conv2d
  File "/home/yong/FCOS/FCOS/maskrcnn_benchmark/layers/__init__.py", line 9, in <module>
    from .nms import nms
  File "/home/yong/FCOS/FCOS/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /home/yong/FCOS/FCOS/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

**Comment by studyharderer** [comment]
Dear author，Thank you for your sharing code, I am meeting this problem, how can I solve it?

**Comment by tianzhi0549** [comment]
@studyharderer Please make sure you are using the same pyton and pytorch version as you compiled the project. Please refer https://github.com/facebookresearch/maskrcnn-benchmark/issues/119.
