### ISSUE TITLE
Using EfficientNet as a backbone

### ISSUE THREAD

**Issue by lukasschmit** [tianzhi0549/FCOS#75]
I am trying to optimize FCOS and I believe using [EfficientNets](https://arxiv.org/pdf/1905.11946.pdf) as a backbone in place of ResNet would help, especially with inference speed.

The problem is that EfficientNet-B0 has 9 stages. Besides creating a config file for it, I assume other code must be changed s.t. the entire FPN is represented (pixel level to higher level). What is the best way to go about modifying this? Is it better to only take 5 (probably the odd) stages from EfficientNet, or does it make more sense to use all 9?

Thanks!

**Comment by lukasschmit** [comment]
![image](https://user-images.githubusercontent.com/4791204/60303190-a173c980-98ea-11e9-9d77-c0bfdc4d7e5c.png)

EfficientNet-B0 architecture for reference

**Comment by tianzhi0549** [comment]
@lukasschmit You only need to use stage 6, 7 and 8 in EfficientNets, which correspond to C3, C4 and C5 in ResNets.

**Comment by tianzhi0549** [comment]
@lukasschmit For your information, we have released faster MobileNet based models.

**Comment by karanchahal** [comment]
For optimisation, can we run a trace of the model with Torchscript currently ? I would like to attain a 8 bit quantised version of this model. What changes do you think are needed ?

**Comment by tianzhi0549** [comment]
@karanchahal I am not familiar with Torchscript. But I think you can just try it. If you encounter any issues, just post them here. Maybe I can help you.

**Comment by liuyizhuang** [comment]
hello ,i also have a issue. py3.6.8，torch1.1.0 ,cuda9

Installing collected packages: fcos
  Running setup.py install for fcos ... error
    ERROR: Complete output from command /usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-n4exwr7n/fcos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-88lpo5bw/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/fcos
    copying fcos/fcos.py -> build/lib.linux-x86_64-3.6/fcos
    copying fcos/__init__.py -> build/lib.linux-x86_64-3.6/fcos
    creating build/lib.linux-x86_64-3.6/fcos_core
    copying fcos_core/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core
    creating build/lib.linux-x86_64-3.6/fcos_core/engine
    copying fcos_core/engine/inference.py -> build/lib.linux-x86_64-3.6/fcos_core/engine
    copying fcos_core/engine/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/engine
    copying fcos_core/engine/trainer.py -> build/lib.linux-x86_64-3.6/fcos_core/engine
    creating build/lib.linux-x86_64-3.6/fcos_core/data
    copying fcos_core/data/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/data
    copying fcos_core/data/collate_batch.py -> build/lib.linux-x86_64-3.6/fcos_core/data
    copying fcos_core/data/build.py -> build/lib.linux-x86_64-3.6/fcos_core/data
    creating build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/imports.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/timer.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/comm.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/miscellaneous.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/cv2_util.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/checkpoint.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/c2_model_loading.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/env.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/logger.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/metric_logger.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/collect_env.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/registry.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/model_serialization.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    copying fcos_core/utils/model_zoo.py -> build/lib.linux-x86_64-3.6/fcos_core/utils
    creating build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/iou_loss.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/smooth_l1_loss.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/misc.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/roi_pool.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/batch_norm.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/roi_align.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/_utils.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/sigmoid_focal_loss.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/nms.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    copying fcos_core/layers/scale.py -> build/lib.linux-x86_64-3.6/fcos_core/layers
    creating build/lib.linux-x86_64-3.6/fcos_core/solver
    copying fcos_core/solver/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/solver
    copying fcos_core/solver/lr_scheduler.py -> build/lib.linux-x86_64-3.6/fcos_core/solver
    copying fcos_core/solver/build.py -> build/lib.linux-x86_64-3.6/fcos_core/solver
    creating build/lib.linux-x86_64-3.6/fcos_core/structures
    copying fcos_core/structures/image_list.py -> build/lib.linux-x86_64-3.6/fcos_core/structures
    copying fcos_core/structures/boxlist_ops.py -> build/lib.linux-x86_64-3.6/fcos_core/structures
    copying fcos_core/structures/bounding_box.py -> build/lib.linux-x86_64-3.6/fcos_core/structures
    copying fcos_core/structures/keypoint.py -> build/lib.linux-x86_64-3.6/fcos_core/structures
    copying fcos_core/structures/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/structures
    copying fcos_core/structures/segmentation_mask.py -> build/lib.linux-x86_64-3.6/fcos_core/structures
    creating build/lib.linux-x86_64-3.6/fcos_core/config
    copying fcos_core/config/paths_catalog.py -> build/lib.linux-x86_64-3.6/fcos_core/config
    copying fcos_core/config/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/config
    copying fcos_core/config/defaults.py -> build/lib.linux-x86_64-3.6/fcos_core/config
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling
    copying fcos_core/modeling/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling
    copying fcos_core/modeling/balanced_positive_negative_sampler.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling
    copying fcos_core/modeling/utils.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling
    copying fcos_core/modeling/poolers.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling
    copying fcos_core/modeling/matcher.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling
    copying fcos_core/modeling/box_coder.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling
    copying fcos_core/modeling/registry.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling
    copying fcos_core/modeling/make_layers.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling
    creating build/lib.linux-x86_64-3.6/fcos_core/data/datasets
    copying fcos_core/data/datasets/list_dataset.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets
    copying fcos_core/data/datasets/coco.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets
    copying fcos_core/data/datasets/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets
    copying fcos_core/data/datasets/concat_dataset.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets
    copying fcos_core/data/datasets/voc.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets
    creating build/lib.linux-x86_64-3.6/fcos_core/data/samplers
    copying fcos_core/data/samplers/distributed.py -> build/lib.linux-x86_64-3.6/fcos_core/data/samplers
    copying fcos_core/data/samplers/iteration_based_batch_sampler.py -> build/lib.linux-x86_64-3.6/fcos_core/data/samplers
    copying fcos_core/data/samplers/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/data/samplers
    copying fcos_core/data/samplers/grouped_batch_sampler.py -> build/lib.linux-x86_64-3.6/fcos_core/data/samplers
    creating build/lib.linux-x86_64-3.6/fcos_core/data/transforms
    copying fcos_core/data/transforms/transforms.py -> build/lib.linux-x86_64-3.6/fcos_core/data/transforms
    copying fcos_core/data/transforms/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/data/transforms
    copying fcos_core/data/transforms/build.py -> build/lib.linux-x86_64-3.6/fcos_core/data/transforms
    creating build/lib.linux-x86_64-3.6/fcos_core/data/datasets/evaluation
    copying fcos_core/data/datasets/evaluation/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets/evaluation
    creating build/lib.linux-x86_64-3.6/fcos_core/data/datasets/evaluation/voc
    copying fcos_core/data/datasets/evaluation/voc/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets/evaluation/voc
    copying fcos_core/data/datasets/evaluation/voc/voc_eval.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets/evaluation/voc
    creating build/lib.linux-x86_64-3.6/fcos_core/data/datasets/evaluation/coco
    copying fcos_core/data/datasets/evaluation/coco/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets/evaluation/coco
    copying fcos_core/data/datasets/evaluation/coco/coco_eval.py -> build/lib.linux-x86_64-3.6/fcos_core/data/datasets/evaluation/coco
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling/backbone
    copying fcos_core/modeling/backbone/fbnet_builder.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/backbone
    copying fcos_core/modeling/backbone/fpn.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/backbone
    copying fcos_core/modeling/backbone/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/backbone
    copying fcos_core/modeling/backbone/fbnet_modeldef.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/backbone
    copying fcos_core/modeling/backbone/backbone.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/backbone
    copying fcos_core/modeling/backbone/fbnet.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/backbone
    copying fcos_core/modeling/backbone/mobilenet.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/backbone
    copying fcos_core/modeling/backbone/resnet.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/backbone
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn
    copying fcos_core/modeling/rpn/inference.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn
    copying fcos_core/modeling/rpn/loss.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn
    copying fcos_core/modeling/rpn/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn
    copying fcos_core/modeling/rpn/rpn.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn
    copying fcos_core/modeling/rpn/utils.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn
    copying fcos_core/modeling/rpn/anchor_generator.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling/detector
    copying fcos_core/modeling/detector/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/detector
    copying fcos_core/modeling/detector/detectors.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/detector
    copying fcos_core/modeling/detector/generalized_rcnn.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/detector
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads
    copying fcos_core/modeling/roi_heads/roi_heads.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads
    copying fcos_core/modeling/roi_heads/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/fcos
    copying fcos_core/modeling/rpn/fcos/fcos.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/fcos
    copying fcos_core/modeling/rpn/fcos/inference.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/fcos
    copying fcos_core/modeling/rpn/fcos/loss.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/fcos
    copying fcos_core/modeling/rpn/fcos/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/fcos
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/retinanet
    copying fcos_core/modeling/rpn/retinanet/retinanet.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/retinanet
    copying fcos_core/modeling/rpn/retinanet/inference.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/retinanet
    copying fcos_core/modeling/rpn/retinanet/loss.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/retinanet
    copying fcos_core/modeling/rpn/retinanet/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/rpn/retinanet
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/mask_head
    copying fcos_core/modeling/roi_heads/mask_head/inference.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/mask_head
    copying fcos_core/modeling/roi_heads/mask_head/loss.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/mask_head
    copying fcos_core/modeling/roi_heads/mask_head/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/mask_head
    copying fcos_core/modeling/roi_heads/mask_head/roi_mask_predictors.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/mask_head
    copying fcos_core/modeling/roi_heads/mask_head/roi_mask_feature_extractors.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/mask_head
    copying fcos_core/modeling/roi_heads/mask_head/mask_head.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/mask_head
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/box_head
    copying fcos_core/modeling/roi_heads/box_head/inference.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/box_head
    copying fcos_core/modeling/roi_heads/box_head/roi_box_feature_extractors.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/box_head
    copying fcos_core/modeling/roi_heads/box_head/loss.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/box_head
    copying fcos_core/modeling/roi_heads/box_head/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/box_head
    copying fcos_core/modeling/roi_heads/box_head/roi_box_predictors.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/box_head
    copying fcos_core/modeling/roi_heads/box_head/box_head.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/box_head
    creating build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/keypoint_head
    copying fcos_core/modeling/roi_heads/keypoint_head/roi_keypoint_predictors.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/keypoint_head
    copying fcos_core/modeling/roi_heads/keypoint_head/inference.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/keypoint_head
    copying fcos_core/modeling/roi_heads/keypoint_head/loss.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/keypoint_head
    copying fcos_core/modeling/roi_heads/keypoint_head/__init__.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/keypoint_head
    copying fcos_core/modeling/roi_heads/keypoint_head/keypoint_head.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/keypoint_head
    copying fcos_core/modeling/roi_heads/keypoint_head/roi_keypoint_feature_extractors.py -> build/lib.linux-x86_64-3.6/fcos_core/modeling/roi_heads/keypoint_head
    running egg_info
    writing fcos.egg-info/PKG-INFO
    writing dependency_links to fcos.egg-info/dependency_links.txt
    writing requirements to fcos.egg-info/requires.txt
    writing top-level names to fcos.egg-info/top_level.txt
    reading manifest file 'fcos.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'fcos.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.6/fcos/bin
    copying fcos/bin/fcos -> build/lib.linux-x86_64-3.6/fcos/bin
    creating build/lib.linux-x86_64-3.6/fcos/configs
    copying fcos/configs/fcos_R_101_FPN_2x.yaml -> build/lib.linux-x86_64-3.6/fcos/configs
    copying fcos/configs/fcos_R_50_FPN_1x.yaml -> build/lib.linux-x86_64-3.6/fcos/configs
    copying fcos/configs/fcos_X_101_32x8d_FPN_2x.yaml -> build/lib.linux-x86_64-3.6/fcos/configs
    copying fcos/configs/fcos_X_101_64x4d_FPN_2x.yaml -> build/lib.linux-x86_64-3.6/fcos/configs
    copying fcos/configs/fcos_bn_bs16_MNV2_FPN_1x.yaml -> build/lib.linux-x86_64-3.6/fcos/configs
    copying fcos/configs/fcos_syncbn_bs32_MNV2_FPN_1x.yaml -> build/lib.linux-x86_64-3.6/fcos/configs
    copying fcos/configs/fcos_syncbn_bs32_c128_MNV2_FPN_1x.yaml -> build/lib.linux-x86_64-3.6/fcos/configs
    copying fcos/configs/fcos_syncbn_bs32_c128_ms_MNV2_FPN_1x.yaml -> build/lib.linux-x86_64-3.6/fcos/configs
    copying fcos/configs/fcos_syncbn_bs64_c128_ms_MNV2_FPN_1x.yaml -> build/lib.linux-x86_64-3.6/fcos/configs
    creating build/lib.linux-x86_64-3.6/fcos_core/csrc
    copying fcos_core/csrc/ROIAlign.h -> build/lib.linux-x86_64-3.6/fcos_core/csrc
    copying fcos_core/csrc/ROIPool.h -> build/lib.linux-x86_64-3.6/fcos_core/csrc
    copying fcos_core/csrc/SigmoidFocalLoss.h -> build/lib.linux-x86_64-3.6/fcos_core/csrc
    copying fcos_core/csrc/nms.h -> build/lib.linux-x86_64-3.6/fcos_core/csrc
    copying fcos_core/csrc/vision.cpp -> build/lib.linux-x86_64-3.6/fcos_core/csrc
    creating build/lib.linux-x86_64-3.6/fcos_core/csrc/cpu
    copying fcos_core/csrc/cpu/ROIAlign_cpu.cpp -> build/lib.linux-x86_64-3.6/fcos_core/csrc/cpu
    copying fcos_core/csrc/cpu/nms_cpu.cpp -> build/lib.linux-x86_64-3.6/fcos_core/csrc/cpu
    copying fcos_core/csrc/cpu/vision.h -> build/lib.linux-x86_64-3.6/fcos_core/csrc/cpu
    creating build/lib.linux-x86_64-3.6/fcos_core/csrc/cuda
    copying fcos_core/csrc/cuda/ROIAlign_cuda.cu -> build/lib.linux-x86_64-3.6/fcos_core/csrc/cuda
    copying fcos_core/csrc/cuda/ROIPool_cuda.cu -> build/lib.linux-x86_64-3.6/fcos_core/csrc/cuda
    copying fcos_core/csrc/cuda/SigmoidFocalLoss_cuda.cu -> build/lib.linux-x86_64-3.6/fcos_core/csrc/cuda
    copying fcos_core/csrc/cuda/nms.cu -> build/lib.linux-x86_64-3.6/fcos_core/csrc/cuda
    copying fcos_core/csrc/cuda/vision.h -> build/lib.linux-x86_64-3.6/fcos_core/csrc/cuda
    running build_ext
    building 'fcos_core._C' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/fcos_core
    creating build/temp.linux-x86_64-3.6/fcos_core/csrc
    creating build/temp.linux-x86_64-3.6/fcos_core/csrc/cpu
    creating build/temp.linux-x86_64-3.6/fcos_core/csrc/cuda
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -Ifcos_core/csrc -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c fcos_core/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/fcos_core/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    In file included from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/Device.h:3:0,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:6,
                     from fcos_core/csrc/cpu/vision.h:3,
                     from fcos_core/csrc/nms.h:3,
                     from fcos_core/csrc/vision.cpp:2:
    /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/python_headers.h:9:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-n4exwr7n/fcos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-88lpo5bw/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-n4exwr7n/fcos/


> @karanchahal I am not familiar with Torchscript. But I think you can just try it. If you encounter any issues, just post them here. Maybe I can help you.

**Comment by haibochina** [comment]
Hi, I met this error when I change the backbone to efficientdet. The error always in bifpn, why the upsampled size do not match?

Traceback (most recent call last):
  File "tools/train_net.py", line 181, in <module>
    main()
  File "tools/train_net.py", line 174, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 80, in train
    arguments,
  File "/home/semtp/notebooks/EfficientDet_FCOS/fcos_core/engine/trainer.py", line 69, in do_train
    loss_dict = model(images, targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/semtp/notebooks/EfficientDet_FCOS/fcos_core/modeling/detector/generalized_rcnn.py", line 49, in forward
    features = self.backbone(images.tensors)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/semtp/notebooks/EfficientDet_FCOS/fcos_core/modeling/backbone/efficientdet.py", line 217, in forward
    features = self.bifpn(features)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/semtp/notebooks/EfficientDet_FCOS/fcos_core/modeling/backbone/efficientdet.py", line 89, in forward
    p5_up = self.conv5_up(weight[0] * p5_in + weight[1] * self.p5_upsample(p6_up))
RuntimeError: The size of tensor a (11) must match the size of tensor b (12) at non-singleton dimension 2
