### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by qianzhang2018** [tianzhi0549/FCOS#79]
Traceback (most recent call last):
  File "tools/train_net.py", line 176, in <module>
    main()
  File "tools/train_net.py", line 169, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 75, in train
    arguments,
  File "/home/administrator/USPIntern/zq/FCOS/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/administrator/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/administrator/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/administrator/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/administrator/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/administrator/.local/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 81, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/administrator/USPIntern/zq/FCOS/maskrcnn_benchmark/data/datasets/coco.py", line 107, in __getitem__
    target = target.clip_to_image(remove_empty=True)
  File "/home/administrator/USPIntern/zq/FCOS/maskrcnn_benchmark/structures/bounding_box.py", line 223, in clip_to_image
    return self[keep]
  File "/home/administrator/USPIntern/zq/FCOS/maskrcnn_benchmark/structures/bounding_box.py", line 208, in __getitem__
    bbox.add_field(k, v[item])
  File "/home/administrator/USPIntern/zq/FCOS/maskrcnn_benchmark/structures/segmentation_mask.py", line 513, in __getitem__
    selected_instances = self.instances.__getitem__(item)
  File "/home/administrator/USPIntern/zq/FCOS/maskrcnn_benchmark/structures/segmentation_mask.py", line 422, in __getitem__
    selected_polygons.append(self.polygons[i])
IndexError: list index out of range

can you help me ?

**Comment by tianzhi0549** [comment]
@qianzhang2018 We don't need mask annotations. You can remove this line https://github.com/tianzhi0549/FCOS/blob/928c610dbae256242a2514fe212f9b10cc6fe0fc/maskrcnn_benchmark/data/datasets/coco.py#L84 to avoid the error.

**Comment by qianzhang2018** [comment]
@tianzhi0549 it works.Thanks,it is very kind of you.

**Comment by Kongsea** [comment]
In my case, line 83 and 84 both need to be removed to avoid this error:
```
masks = SegmentationMask(masks, img.size, mode='poly')
target.add_field("masks", masks)
```

**Comment by imyhxy** [comment]
@tianzhi0549 Why only some users will encounter this problem？

**Comment by tianzhi0549** [comment]
@imyhxy It might be related to their torchvision version.

**Comment by jinfagang** [comment]
@tianzhi0549  I am training CenterMask and got this error, weired. And I do need mask annotation.
