### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.FCOS_ON'

### ISSUE THREAD

**Issue by NiNiZhang17** [tianzhi0549/FCOS#92]
when i try to run demo.py, I get the error:
Traceback (most recent call last):
  File "demo/fcos_demo.py", line 109, in <module>
    main()
  File "demo/fcos_demo.py", line 48, in main
    cfg.merge_from_file(args.config_file)
  File "/home/amax/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages                                                                             /yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/amax/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages                                                                             /yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/amax/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages                                                                             /yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/amax/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages                                                                             /yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
i try to create an new environment,but it didn't work,Dose anyone know how to fix this problem?

**Comment by tianzhi0549** [comment]
@NiNiZhang17 Please try to run `python setup.py build develop` again in your new environment.

**Comment by NiNiZhang17** [comment]
> @NiNiZhang17 Please try to run python setup.py build develop again in your new environment.
thank you very much, the problem is solved.i installed envirment by the code your gave,the error may be caused by code downloaded  from  https://github.com/cocodataset/cocoapi.git.

**Comment by tianzhi0549** [comment]
@NiNiZhang17 Happy to know you have solved it.
